version: '3.3'

services:
  django_web:
    image: jonathanmpspark/jenkins-demo
    build:
        context: .
        dockerfile: ./docker/web/Dockerfile
    container_name: django_web
    ports:
      - '8080:80'
    volumes:
       - .:/app
    command: /start
    restart: unless-stopped